version: '3'
services:
  nosql_converter:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    image: allensyk/nosql_converter:0.5
    container_name: converter
    environment:
      DB_HOST: 192.168.31.73
      DB_PORT: 3306
      DB_USERNAME: allen
      DB_PASSWORD: aldbpw
      MONGO_HOST: 192.168.31.73
      MONGO_PORT: 27017
