DB:
  host: 192.168.31.73
  password: aldbpw
  port: 3306
  schema: gambling_simulation
  user: allen
crawler:
  dateFormat: '%Y%m%d'
  urlPattern: https://www.playsport.cc/predictgame.php?action=scale&allianceid={game_type}&gametime={game_date}&sid={group_type}
data_updater:
  update_period: 24
logging:
  level: DEBUG
mongoDb:
  host: 192.168.31.73
  password: password
  port: 27017
  username: allen
