joined_tables = ['game_data',
                 'game_judgement',
                 'prediction_data_all_member',
                 'prediction_data_all_prefer',
                 'prediction_data_more_than_sixty',
                 'prediction_data_top_100',
                 'prediction_judgement_all_member',
                 'prediction_judgement_all_prefer',
                 'prediction_judgement_more_than_sixty',
                 'prediction_judgement_top_100']

joined_columns = [
    'game_data.id',
    'game_data.game_date',
    'game_data.gamble_id',
    'game_data.game_type',
    'game_data.play_time',
    'game_data.AM_PM',
    'game_data.guest',
    'game_data.host',
    'game_data.guest_score',
    'game_data.host_score',
    'game_data.national_total_point_threshold',
    'game_data.national_host_point_spread',
    'game_data.win_if_meet_spread_point',
    'game_data.response_ratio_if_hit_spread_point',
    'game_data.local_host_point_spread',
    'game_data.local_host_point_spread_response_ratio',
    'game_data.local_total_point_threshold',
    'game_data.local_total_point_threshold_response_ratio',
    'game_data.local_origin_guest_response_ratio',
    'game_data.local_origin_host_response_ratio',
    'game_judgement.host_win_original',
    'game_judgement.host_win_point_spread_national',
    'game_judgement.host_win_point_spread_local',
    'game_judgement.over_total_point_national',
    'game_judgement.over_total_point_local',
    'prediction_data_all_member.percentage_national_point_spread_guest AS percentage_national_point_spread_guest__all_member',
    'prediction_data_all_member.population_national_point_spread_guest AS population_national_point_spread_guest__all_member',
    'prediction_data_all_member.percentage_national_total_point_over AS percentage_national_total_point_over__all_member',
    'prediction_data_all_member.population_national_total_point_over AS population_national_total_point_over__all_member',
    'prediction_data_all_member.percentage_local_point_spread_guest AS percentage_local_point_spread_guest__all_member',
    'prediction_data_all_member.population_local_point_spread_guest AS population_local_point_spread_guest__all_member',
    'prediction_data_all_member.percentage_local_total_point_over AS percentage_local_total_point_over__all_member',
    'prediction_data_all_member.population_local_total_point_over AS population_local_total_point_over__all_member',
    'prediction_data_all_member.percentage_local_original_guest AS percentage_local_original_guest__all_member',
    'prediction_data_all_member.population_local_original_guest AS population_local_original_guest__all_member',
    'prediction_data_all_member.percentage_national_point_spread_host AS percentage_national_point_spread_host__all_member',
    'prediction_data_all_member.population_national_point_spread_host AS population_national_point_spread_host__all_member',
    'prediction_data_all_member.percentage_national_total_point_under AS percentage_national_total_point_under__all_member',
    'prediction_data_all_member.population_national_total_point_under AS population_national_total_point_under__all_member',
    'prediction_data_all_member.percentage_local_point_spread_host AS percentage_local_point_spread_host__all_member',
    'prediction_data_all_member.population_local_point_spread_host AS population_local_point_spread_host__all_member',
    'prediction_data_all_member.percentage_local_total_point_under AS percentage_local_total_point_under__all_member',
    'prediction_data_all_member.population_local_total_point_under AS population_local_total_point_under__all_member',
    'prediction_data_all_member.percentage_local_original_host AS percentage_local_original_host__all_member',
    'prediction_data_all_member.population_local_original_host AS population_local_original_host__all_member',
    'prediction_data_all_prefer.percentage_national_point_spread_guest AS percentage_national_point_spread_guest__all_prefer',
    'prediction_data_all_prefer.population_national_point_spread_guest AS population_national_point_spread_guest__all_prefer',
    'prediction_data_all_prefer.percentage_national_total_point_over AS percentage_national_total_point_over__all_prefer',
    'prediction_data_all_prefer.population_national_total_point_over AS population_national_total_point_over__all_prefer',
    'prediction_data_all_prefer.percentage_local_point_spread_guest AS percentage_local_point_spread_guest__all_prefer',
    'prediction_data_all_prefer.population_local_point_spread_guest AS population_local_point_spread_guest__all_prefer',
    'prediction_data_all_prefer.percentage_local_total_point_over AS percentage_local_total_point_over__all_prefer',
    'prediction_data_all_prefer.population_local_total_point_over AS population_local_total_point_over__all_prefer',
    'prediction_data_all_prefer.percentage_local_original_guest AS percentage_local_original_guest__all_prefer',
    'prediction_data_all_prefer.population_local_original_guest AS population_local_original_guest__all_prefer',
    'prediction_data_all_prefer.percentage_national_point_spread_host AS percentage_national_point_spread_host__all_prefer',
    'prediction_data_all_prefer.population_national_point_spread_host AS population_national_point_spread_host__all_prefer',
    'prediction_data_all_prefer.percentage_national_total_point_under AS percentage_national_total_point_under__all_prefer',
    'prediction_data_all_prefer.population_national_total_point_under AS population_national_total_point_under__all_prefer',
    'prediction_data_all_prefer.percentage_local_point_spread_host AS percentage_local_point_spread_host__all_prefer',
    'prediction_data_all_prefer.population_local_point_spread_host AS population_local_point_spread_host__all_prefer',
    'prediction_data_all_prefer.percentage_local_total_point_under AS percentage_local_total_point_under__all_prefer',
    'prediction_data_all_prefer.population_local_total_point_under AS population_local_total_point_under__all_prefer',
    'prediction_data_all_prefer.percentage_local_original_host AS percentage_local_original_host__all_prefer',
    'prediction_data_all_prefer.population_local_original_host AS population_local_original_host__all_prefer',
    'prediction_data_more_than_sixty.percentage_national_point_spread_guest AS percentage_national_point_spread_guest__more_than_sixty',
    'prediction_data_more_than_sixty.population_national_point_spread_guest AS population_national_point_spread_guest__more_than_sixty',
    'prediction_data_more_than_sixty.percentage_national_total_point_over AS percentage_national_total_point_over__more_than_sixty',
    'prediction_data_more_than_sixty.population_national_total_point_over AS population_national_total_point_over__more_than_sixty',
    'prediction_data_more_than_sixty.percentage_local_point_spread_guest AS percentage_local_point_spread_guest__more_than_sixty',
    'prediction_data_more_than_sixty.population_local_point_spread_guest AS population_local_point_spread_guest__more_than_sixty',
    'prediction_data_more_than_sixty.percentage_local_total_point_over AS percentage_local_total_point_over__more_than_sixty',
    'prediction_data_more_than_sixty.population_local_total_point_over AS population_local_total_point_over__more_than_sixty',
    'prediction_data_more_than_sixty.percentage_local_original_guest AS percentage_local_original_guest__more_than_sixty',
    'prediction_data_more_than_sixty.population_local_original_guest AS population_local_original_guest__more_than_sixty',
    'prediction_data_more_than_sixty.percentage_national_point_spread_host AS percentage_national_point_spread_host__more_than_sixty',
    'prediction_data_more_than_sixty.population_national_point_spread_host AS population_national_point_spread_host__more_than_sixty',
    'prediction_data_more_than_sixty.percentage_national_total_point_under AS percentage_national_total_point_under__more_than_sixty',
    'prediction_data_more_than_sixty.population_national_total_point_under AS population_national_total_point_under__more_than_sixty',
    'prediction_data_more_than_sixty.percentage_local_point_spread_host AS percentage_local_point_spread_host__more_than_sixty',
    'prediction_data_more_than_sixty.population_local_point_spread_host AS population_local_point_spread_host__more_than_sixty',
    'prediction_data_more_than_sixty.percentage_local_total_point_under AS percentage_local_total_point_under__more_than_sixty',
    'prediction_data_more_than_sixty.population_local_total_point_under AS population_local_total_point_under__more_than_sixty',
    'prediction_data_more_than_sixty.percentage_local_original_host AS percentage_local_original_host__more_than_sixty',
    'prediction_data_more_than_sixty.population_local_original_host AS population_local_original_host__more_than_sixty',
    'prediction_data_top_100.percentage_national_point_spread_guest AS percentage_national_point_spread_guest__top_100',
    'prediction_data_top_100.population_national_point_spread_guest AS population_national_point_spread_guest__top_100',
    'prediction_data_top_100.percentage_national_total_point_over AS percentage_national_total_point_over__top_100',
    'prediction_data_top_100.population_national_total_point_over AS population_national_total_point_over__top_100',
    'prediction_data_top_100.percentage_local_point_spread_guest AS percentage_local_point_spread_guest__top_100',
    'prediction_data_top_100.population_local_point_spread_guest AS population_local_point_spread_guest__top_100',
    'prediction_data_top_100.percentage_local_total_point_over AS percentage_local_total_point_over__top_100',
    'prediction_data_top_100.population_local_total_point_over AS population_local_total_point_over__top_100',
    'prediction_data_top_100.percentage_local_original_guest AS percentage_local_original_guest__top_100',
    'prediction_data_top_100.population_local_original_guest AS population_local_original_guest__top_100',
    'prediction_data_top_100.percentage_national_point_spread_host AS percentage_national_point_spread_host__top_100',
    'prediction_data_top_100.population_national_point_spread_host AS population_national_point_spread_host__top_100',
    'prediction_data_top_100.percentage_national_total_point_under AS percentage_national_total_point_under__top_100',
    'prediction_data_top_100.population_national_total_point_under AS population_national_total_point_under__top_100',
    'prediction_data_top_100.percentage_local_point_spread_host AS percentage_local_point_spread_host__top_100',
    'prediction_data_top_100.population_local_point_spread_host AS population_local_point_spread_host__top_100',
    'prediction_data_top_100.percentage_local_total_point_under AS percentage_local_total_point_under__top_100',
    'prediction_data_top_100.population_local_total_point_under AS population_local_total_point_under__top_100',
    'prediction_data_top_100.percentage_local_original_host AS percentage_local_original_host__top_100',
    'prediction_data_top_100.population_local_original_host AS population_local_original_host__top_100',
    'prediction_judgement_all_member.national_point_spread_result AS national_point_spread_result__all_member',
    'prediction_judgement_all_member.national_point_spread_percentage AS national_point_spread_percentage__all_member',
    'prediction_judgement_all_member.national_point_spread_population AS national_point_spread_population__all_member',
    'prediction_judgement_all_member.national_total_point_result AS national_total_point_result__all_member',
    'prediction_judgement_all_member.national_total_point_percentage AS national_total_point_percentage__all_member',
    'prediction_judgement_all_member.national_total_point_population AS national_total_point_population__all_member',
    'prediction_judgement_all_member.local_total_point_result AS local_total_point_result__all_member',
    'prediction_judgement_all_member.local_total_point_percentage AS local_total_point_percentage__all_member',
    'prediction_judgement_all_member.local_total_point_population AS local_total_point_population__all_member',
    'prediction_judgement_all_member.local_point_spread_result AS local_point_spread_result__all_member',
    'prediction_judgement_all_member.local_point_spread_percentage AS local_point_spread_percentage__all_member',
    'prediction_judgement_all_member.local_point_spread_population AS local_point_spread_population__all_member',
    'prediction_judgement_all_member.local_original_result AS local_original_result__all_member',
    'prediction_judgement_all_member.local_original_percentage AS local_original_percentage__all_member',
    'prediction_judgement_all_member.local_original_population AS local_original_population__all_member',
    'prediction_judgement_all_prefer.national_point_spread_result AS national_point_spread_result__all_prefer',
    'prediction_judgement_all_prefer.national_point_spread_percentage AS national_point_spread_percentage__all_prefer',
    'prediction_judgement_all_prefer.national_point_spread_population AS national_point_spread_population__all_prefer',
    'prediction_judgement_all_prefer.national_total_point_result AS national_total_point_result__all_prefer',
    'prediction_judgement_all_prefer.national_total_point_percentage AS national_total_point_percentage__all_prefer',
    'prediction_judgement_all_prefer.national_total_point_population AS national_total_point_population__all_prefer',
    'prediction_judgement_all_prefer.local_total_point_result AS local_total_point_result__all_prefer',
    'prediction_judgement_all_prefer.local_total_point_percentage AS local_total_point_percentage__all_prefer',
    'prediction_judgement_all_prefer.local_total_point_population AS local_total_point_population__all_prefer',
    'prediction_judgement_all_prefer.local_point_spread_result AS local_point_spread_result__all_prefer',
    'prediction_judgement_all_prefer.local_point_spread_percentage AS local_point_spread_percentage__all_prefer',
    'prediction_judgement_all_prefer.local_point_spread_population AS local_point_spread_population__all_prefer',
    'prediction_judgement_all_prefer.local_original_result AS local_original_result__all_prefer',
    'prediction_judgement_all_prefer.local_original_percentage AS local_original_percentage__all_prefer',
    'prediction_judgement_all_prefer.local_original_population AS local_original_population__all_prefer',
    'prediction_judgement_more_than_sixty.national_point_spread_result AS national_point_spread_result__more_than_sixty',
    'prediction_judgement_more_than_sixty.national_point_spread_percentage AS national_point_spread_percentage__more_than_sixty',
    'prediction_judgement_more_than_sixty.national_point_spread_population AS national_point_spread_population__more_than_sixty',
    'prediction_judgement_more_than_sixty.national_total_point_result AS national_total_point_result__more_than_sixty',
    'prediction_judgement_more_than_sixty.national_total_point_percentage AS national_total_point_percentage__more_than_sixty',
    'prediction_judgement_more_than_sixty.national_total_point_population AS national_total_point_population__more_than_sixty',
    'prediction_judgement_more_than_sixty.local_total_point_result AS local_total_point_result__more_than_sixty',
    'prediction_judgement_more_than_sixty.local_total_point_percentage AS local_total_point_percentage__more_than_sixty',
    'prediction_judgement_more_than_sixty.local_total_point_population AS local_total_point_population__more_than_sixty',
    'prediction_judgement_more_than_sixty.local_point_spread_result AS local_point_spread_result__more_than_sixty',
    'prediction_judgement_more_than_sixty.local_point_spread_percentage AS local_point_spread_percentage__more_than_sixty',
    'prediction_judgement_more_than_sixty.local_point_spread_population AS local_point_spread_population__more_than_sixty',
    'prediction_judgement_more_than_sixty.local_original_result AS local_original_result__more_than_sixty',
    'prediction_judgement_more_than_sixty.local_original_percentage AS local_original_percentage__more_than_sixty',
    'prediction_judgement_more_than_sixty.local_original_population AS local_original_population__more_than_sixty',
    'prediction_judgement_top_100.national_point_spread_result AS national_point_spread_result__top_100',
    'prediction_judgement_top_100.national_point_spread_percentage AS national_point_spread_percentage__top_100',
    'prediction_judgement_top_100.national_point_spread_population AS national_point_spread_population__top_100',
    'prediction_judgement_top_100.national_total_point_result AS national_total_point_result__top_100',
    'prediction_judgement_top_100.national_total_point_percentage AS national_total_point_percentage__top_100',
    'prediction_judgement_top_100.national_total_point_population AS national_total_point_population__top_100',
    'prediction_judgement_top_100.local_total_point_result AS local_total_point_result__top_100',
    'prediction_judgement_top_100.local_total_point_percentage AS local_total_point_percentage__top_100',
    'prediction_judgement_top_100.local_total_point_population AS local_total_point_population__top_100',
    'prediction_judgement_top_100.local_point_spread_result AS local_point_spread_result__top_100',
    'prediction_judgement_top_100.local_point_spread_percentage AS local_point_spread_percentage__top_100',
    'prediction_judgement_top_100.local_point_spread_population AS local_point_spread_population__top_100',
    'prediction_judgement_top_100.local_original_result AS local_original_result__top_100',
    'prediction_judgement_top_100.local_original_percentage AS local_original_percentage__top_100',
    'prediction_judgement_top_100.local_original_population AS local_original_population__top_100']
